package.json
close #37 
I have added "types" and "check" scripts, in preparation for the github action
=> scripts added

src/Components/Buttons/HugeButton.tsx
=> Added HugeButton

src/Screens/CreateScreen.tsx
We can now add a household to firebase
=> CreateScreen now adds a household to FB /w id,name,invitecode

src/Navigation/RootNavigator.tsx, src/Screens/DevStartScreen.tsx
For easy navigation during development
=> add TEMP screen for dev period only!

src/Screens/ProfileScreen.tsx
=> 10 a user must be able to enter their name

package-lock.json, package.json, src/Screens/CreateScreen.tsx
In create screen when you press the icon next to the code generated when naming a household
=> copy to clipboard by pressing the code icon

src/Components/Themed.tsx, src/Screens/CreateScreen.tsx, src/Screens/StartScreen.tsx
=> 93 add textinput to darkmode and fix the start screen

package-lock.json, package.json, src/Components/Buttons/BigButton.tsx, src/Screens/ChoreScreen.tsx, src/Screens/CreateScreen.tsx, src/Screens/DetailScreen.tsx, src/Screens/DevStartScreen.tsx, src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Screens/RegisterScreen.tsx, src/Screens/StartScreen.tsx, src/Screens/StatisticsScreen.tsx
close #115 
Will install and change for every Screen as well as BigButton
=> 115 install react native paper

src/Components/Cards/AvatarCard.tsx, src/Components/Cards/ChoreCard.tsx, src/Screens/ProfileScreen.tsx
Har tyvärr inte hittat någon slider till DemandingCard.
=> 120 make card components react native paper

src/Screens/ChoreScreen.tsx, src/Store/choreSlice.ts
Still using NativeBase components though. Will update later when paper is in.
=> add state, input & chore adding to chorepage

src/Screens/ChoreScreen.tsx, src/Screens/CreateScreen.tsx, src/Screens/DetailScreen.tsx, src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Screens/StatisticsScreen.tsx
=> remove colors in stylesheets on screens and remove nativebase components

src/Navigation/RootNavigator.tsx, src/Screens/ChoreScreen.tsx, src/Screens/DevStartScreen.tsx, src/Screens/EditChoreScreen.tsx, src/Screens/HomeScreen.tsx
navigation added, button leading to the screen in homescreen & devstartscreen
no logic to fetch chore yet
=> add screen, button navigating to it in screens

src/Components/Cards/AvatarCard.tsx, src/Data/profile.ts, src/Screens/CreateScreen.tsx, src/Screens/ProfileScreen.tsx, src/Store/householdSlice.ts, src/Store/profileSlice.ts
=> 9 a user should be able to join a household by entering the households code

src/Screens/HomeScreen.tsx, src/Store/choreSlice.ts
fetches chores on a specific household id at the moment
=> 131 create thunk to fetch chores

src/Store/householdSlice.ts
=> add thunk for getting every household which user is a member in

src/Components/Cards/ChoreCard.tsx, src/Screens/DetailScreen.tsx, src/Screens/HomeScreen.tsx, src/Store/choreSlice.ts
showing chores from a fixed id in homescreen and detailscreen atm
=> 140 show some chores in homescreen

src/Data/profile.ts, src/Data/user.ts, src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Store/householdSlice.ts, src/Store/profileSlice.ts, src/Store/userSlice.ts
Made it possible to join a household with the right code if you already join the household, you will be navigated to home screen
logic to add the profile is not done yet
=> 136 join household function

src/Components/filterAvatarList.ts, src/Screens/ProfileScreen.tsx
=> 12 selected avatars

src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Store/householdSlice.ts, src/Store/profileSlice.ts
=> save profiles to array and save household to singleHousehold

src/Screens/EditChoreScreen.tsx, src/Store/choreSlice.ts
Edit chore thunk works as intended
=> 16 an owner must be able to edit a chore

src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Store/profileSlice.ts
check for multiple users with same name doesn't work so it's commented out atm
=> 150 add new profile to firestore

src/Screens/RegisterScreen.tsx
=> Make register screen look like Start screen

src/Data/choreHistory.ts, src/Store/choreHistorySlice.ts, src/Store/choreHsitorySlice.ts, src/Store/store.ts
=> add choreHistorySlice

src/Screens/ChoreScreen.tsx, src/Screens/EditChoreScreen.tsx, src/Store/choreSlice.ts, src/Store/householdSlice.ts
Thunk done, slice is still a work in progress
=> Edit HHname thunk done, slice is still wip

src/Screens/EditChoreScreen.tsx, src/Store/choreSlice.ts
editChore will now remove the original chore from the chore array and replace it with the new update version of the chore
=> ed.Chore replaces original chore with new in array

src/Screens/RegisterScreen.tsx, src/Store/userSlice.ts
Only if the user succeeds in registering!
=> add useeffect to move new users to managerscreen

src/Screens/EditChoreScreen.tsx, src/Screens/HomeScreen.tsx, src/Store/householdSlice.ts
Removes old household and inserts the new
=> Changes household name in DA FIRE BAAASEEE

src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Store/householdSlice.ts, src/Store/profileSlice.ts, src/Store/userSlice.ts
=> 186 show all households a user is in managerscreen

src/Screens/ChoreScreen.tsx
=> 205 style chorescreen

src/Screens/CreateScreen.tsx, src/Screens/ProfileScreen.tsx, src/Screens/RegisterScreen.tsx, src/Store/householdSlice.ts
=> 206 small fix in profile screen and create screen

src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Screens/RegisterScreen.tsx, src/Screens/StartScreen.tsx
=> 211 instead of useeffects

src/Screens/DetailScreen.tsx
Still need more work to mark the right chore as done
=> Can now mark the first chore as done

src/Navigation/RootNavigator.tsx, src/Screens/EditChoreScreen.tsx, src/Screens/HomeScreen.tsx, src/Store/choreSlice.ts
inte syndabocken alls
--
displaying edited chores now works, nav to edit chore screen also works
=> fixed faulty thunk args, add route + id params to editchorescreen

src/Screens/CreateScreen.tsx, src/Screens/ManagerScreen.tsx, src/Screens/ProfileScreen.tsx, src/Store/householdSlice.ts, src/Store/profileSlice.ts
close #228 
make sure that user can't join the same household again & a household is saved in db only when profile has been created
=> User can't join same household, household is added to db after profile is created

src/Screens/DevStartScreen.tsx, src/Screens/EditChoreScreen.tsx, src/Screens/HomeScreen.tsx
=> remove dispatch

src/Screens/CreateScreen.tsx
Minor changes from the figma FOR IMPROVED PERFORMANCE!
=> Create screen looks almost like Figma

src/Screens/DevStartScreen.tsx, src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Store/profileSlice.ts
skipping the icon part since we'll have to revise the design regarding the implementation so that it works like the figma design
=> add thunk to get and set currentprofile upon entering a household

src/Screens/CreateScreen.tsx, src/Screens/DetailScreen.tsx, src/Screens/ManagerScreen.tsx, src/Store/choreHistorySlice.ts, src/Store/profileSlice.ts
will fix some issues and bugs as well as prepare for statistics screen
=> fix some issues and bugs

src/Navigation/RootNavigator.tsx, src/Screens/DetailScreen.tsx, src/Screens/EditChoreScreen.tsx
+ some styling on detailscreen
=> 251 add proper screen titles in rootstack nav

src/Screens/ChoreScreen.tsx
=> Added some stylish styling

src/Components/PieChart.tsx, src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Screens/StatisticsScreen.tsx, src/Store/profileSlice.ts
close #22 
Just needs a filter so that the history shown should be for the current week
=> 22 statistics view current week

src/Components/filterChoreHistory.ts
close #259 
now it only remains to implement this on the StatisticsScreen
=> create function to filter choreHistory for the current week

package-lock.json, package.json, src/Screens/HomeScreen.tsx, src/Screens/StatisticsScreen.tsx, src/Store/choreHistorySlice.ts
=> 267 implement statistics filter

src/Screens/ChoreScreen.tsx
=> Added chorehistory on create of a chore

src/Components/PieChart.tsx, src/Components/filterChoreHistory.ts, src/Navigation/RootNavigator.tsx, src/Screens/StatisticsScreen.tsx, src/Store/choreHistorySlice.ts
=> 296 statistics not shown

src/Screens/ChoreScreen.tsx, src/Screens/EditChoreScreen.tsx
Added some more validation to chore screen and edit screen
=> Add validation

src/Screens/RegisterScreen.tsx
=> RegisterScreen now looks like the figma

src/Screens/ManagerScreen.tsx, src/Store/profileSlice.ts
=> fix issue where current profile gets wrong profile

src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Store/choreHistorySlice.ts, src/Store/choreSlice.ts
=> 284 overdue chore

package-lock.json, src/Screens/CreateScreen.tsx, src/Screens/HomeScreen.tsx, src/Screens/ManagerScreen.tsx, src/Store/choreHistorySlice.ts, src/Store/choreSlice.ts, src/Store/householdSlice.ts
Also fixing the issue of wrong display of chore days in homescreen
=> 323 create a join household action that does everything

src/Screens/HomeScreen.tsx
=> Added the invite code on change household popup

src/Navigation/RootNavigator.tsx, src/Navigation/TopTabsNavigator.tsx, src/Screens/StatisticsScreen.tsx
=> make sure top tab bar looks like figma

README.md
As good as done. Will need to cirkle back later to change and add some stuff, but at least now it exists.
=> add README, nearly completed, cirkle back later

src/Screens/StatisticsScreen.tsx
=> temp fix increasing width, height and padding

src/Store/choreHistorySlice.ts
=> sort arrays and will fix split pie chart issue

src/Navigation/TopTabsNavigator.tsx, src/Screens/HomeScreen.tsx
=> make sure arrows are not shown when not navigation is possible

src/Screens/ChoreScreen.tsx
You can now use commas, periods and exclemation mark when creating a chore
=> Creating chore now allows commas and periods

src/Components/Cards/ChoreCard.tsx, src/Screens/ChoreScreen.tsx, src/Screens/EditChoreScreen.tsx
=> Fixed commas and periods to edit

src/Components/TotalChorePieChart.tsx, src/Screens/StatisticsScreen.tsx
=> fix legend styling
